name: Test Build Deploy

on:
  push:
    branches: [ master ]

env:
  IMAGE: sonhal/fastapi-demo


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: pytest

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag ${IMAGE}:${{ github.sha }} --tag ${IMAGE}:latest .
    - name: Publish Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_HUB_AT: ${{ secrets.DOCKER_HUB_AT }}

      run: |
        docker login --username sonhal --password ${DOCKER_HUB_AT}
        docker push ${IMAGE}
          
          
          
