name: Test Build Deploy

on:
  push:
    branches: [ master ]


env:
  IMAGE: docker.pkg.github.com/datnor-demo-app/master:${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: pytest

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag ${IMAGE} .
    - name: Publish Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${IMAGE}
          
          
          
