name: Test Build Deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: pytest

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag datnor-demo-app:$(date +%s)
    - name: Publish Docker image
      run: |
        docker login -u sonhal -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker tag datnor-demo-app:$(date +%s) docker.pkg.github.com/sonhal/fastapi-demo/datnor-demo-app:0.0.1
        docker push docker.pkg.github.com/sonhal/fastapi-demo/datnor-demo-app:0.0.1
